name: "deploy-pages"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-pages:
    name: "Deploy Pages"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build site
        run: |
          curl -s -S -L https://raw.githubusercontent.com/altlimit/sitegen/master/install.sh | bash
          ~/.altlimit/bin/sitegen -clean -minify
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
